export const LOADING = "LOADING";
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';

export const GET_WITHDRAWALS_SUCCESS = 'GET_WITHDRAWALS_SUCCESS'
export const GET_WITHDRAWALS_ERROR = 'GET_WITHDRAWALS_ERROR'

export const GET_DEPOSITS_SUCCESS = 'GET_DEPOSITS_SUCCESS'
export const GET_DEPOSITS_ERROR = 'GET_DEPOSITS_ERROR'

export const GET_COMMITTED_AMMOUNT_SUCCESS = 'GET_COMMITTED_AMMOUNT_SUCCESS'
export const GET_COMMITTED_AMMOUNT_ERROR = 'GET_COMMITTED_AMMOUNT_ERROR'

export const GET_UNCOMMITTED_AMMOUNT_SUCCESS = 'GET_UNCOMMITTED_AMMOUNT_SUCCESS'
export const GET_UNCOMMITTED_AMMOUNT_ERROR = 'GET_UNCOMMITTED_AMMOUNT_ERROR'

export const GET_TOTAL_ACCOUNT_BALANCE_SUCCESS = 'GET_TOTAL_ACCOUNT_BALANCE_SUCCESS'
export const GET_TOTAL_ACCOUNT_BALANCE_ERROR = 'GET_TOTAL_ACCOUNT_BALANCE_ERROR'

export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS'
export const WITHDRAW_ERROR = 'WITHDRAW_ERROR'

export const DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS'
export const DEPOSIT_ERROR = 'DEPOSIT_ERROR'
