export const LOADING = "LOADING";
export const GET_USER_PROJECTS_ERROR = 'GET_USER_PROJECTS_ERROR'
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS'

export const GET_GLOBAL_PROJECTS_ERROR = 'GET_GLOBAL_PROJECTS_ERROR'
export const GET_GLOBAL_PROJECTS_SUCCESS = 'GET_GLOBAL_PROJECTS_SUCCESS'

export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'

export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR'

export const EDIT_PROJECT_ERROR = 'EDIT_PROJECT_ERROR'
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS'


// Pull Requests
export const GET_PULL_REQUEST_SUCCESS = 'GET_PULL_REQUEST_SUCCESS'
export const GET_PULL_REQUEST_ERROR = 'GET_PULL_REQUEST_ERROR'

export const GET_PROJECT_PULL_REQUESTS_SUCCESS = 'GET_PROJECT_PULL_REQUESTS_SUCCESS'
export const GET_PROJECT_PULL_REQUESTS_ERROR = 'GET_PULL_REQUESTS_ERROR'


export const GET_GLOBAL_PULL_REQUESTS_SUCCESS = 'GET_GLOBAL_PULL_REQUESTS_SUCCESS'
export const GET_GLOBAL_PULL_REQUESTS_ERROR = 'GET_GLOBAL_PULL_REQUESTS_ERROR'


export const CREATE_PULL_REQUEST_SUCCESS = 'CREATE_PULL_REQUEST_SUCCESS'
export const CREATE_PULL_REQUEST_ERROR = 'CREATE_PULL_REQUEST_ERROR'


export const EDIT_PULL_REQUEST_SUCCESS = 'EDIT_PULL_REQUEST_SUCCESS'
export const EDIT_PULL_REQUEST_ERROR = 'EDIT_PULL_REQUEST_ERROR'

export const ASSIGN_PULL_REQUEST_SUCCESS = 'ASSIGN_PULL_REQUEST_SUCCESS'
export const ASSIGN_PULL_REQUEST_ERROR = 'ASSIGN_PULL_REQUEST_ERROR'



// Commits
export const GET_COMMIT_SUCCESS = 'GET_COMMIT_SUCCESS'
export const GET_COMMIT_ERROR = 'GET_COMMIT_ERROR'

export const GET_PROJECT_COMMITS_SUCCESS = 'GET_PROJECT_COMMITS_SUCCESS'
export const GET_PROJECT_COMMITS_ERROR = 'GET_COMMITS_ERROR'


export const GET_GLOBAL_COMMITS_SUCCESS = 'GET_GLOBAL_COMMITS_SUCCESS'
export const GET_GLOBAL_COMMITS_ERROR = 'GET_GLOBAL_COMMITS_ERROR'


export const CREATE_COMMIT_SUCCESS = 'CREATE_COMMIT_SUCCESS'
export const CREATE_COMMIT_ERROR = 'CREATE_COMMIT_ERROR'


export const EDIT_COMMIT_SUCCESS = 'EDIT_COMMIT_SUCCESS'
export const EDIT_COMMIT_ERROR = 'EDIT_COMMIT_ERROR'

export const ASSIGN_COMMIT_SUCCESS = 'ASSIGN_COMMIT_SUCCESS'
export const ASSIGN_COMMIT_ERROR = 'ASSIGN_COMMIT_ERROR'



// Issues
export const GET_ISSUE_SUCCESS = 'GET_ISSUE_SUCCESS'
export const GET_ISSUE_ERROR = 'GET_ISSUE_ERROR'

export const GET_PROJECT_ISSUES_SUCCESS = 'GET_PROJECT_ISSUES_SUCCESS'
export const GET_PROJECT_ISSUES_ERROR = 'GET_ISSUES_ERROR'


export const GET_GLOBAL_ISSUES_SUCCESS = 'GET_GLOBAL_ISSUES_SUCCESS'
export const GET_GLOBAL_ISSUES_ERROR = 'GET_GLOBAL_ISSUES_ERROR'


export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS'
export const CREATE_ISSUE_ERROR = 'CREATE_ISSUE_ERROR'


export const EDIT_ISSUE_SUCCESS = 'EDIT_ISSUE_SUCCESS'
export const EDIT_ISSUE_ERROR = 'EDIT_ISSUE_ERROR'

export const ASSIGN_ISSUE_SUCCESS = 'ASSIGN_ISSUE_SUCCESS'
export const ASSIGN_ISSUE_ERROR = 'ASSIGN_ISSUE_ERROR'



// Branches
export const GET_BRANCH_SUCCESS = 'GET_BRANCH_SUCCESS'
export const GET_BRANCH_ERROR = 'GET_BRANCH_ERROR'

export const GET_PROJECT_BRANCHES_SUCCESS = 'GET_PROJECT_BRANCHES_SUCCESS'
export const GET_PROJECT_BRANCHES_ERROR = 'GET_BRANCHES_ERROR'


export const GET_GLOBAL_BRANCHES_SUCCESS = 'GET_GLOBAL_BRANCHES_SUCCESS'
export const GET_GLOBAL_BRANCHES_ERROR = 'GET_GLOBAL_BRANCHES_ERROR'


export const CREATE_BRANCH_SUCCESS = 'CREATE_BRANCH_SUCCESS'
export const CREATE_BRANCH_ERROR = 'CREATE_BRANCH_ERROR'


export const EDIT_BRANCH_SUCCESS = 'EDIT_BRANCH_SUCCESS'
export const EDIT_BRANCH_ERROR = 'EDIT_BRANCH_ERROR'

export const ASSIGN_BRANCH_SUCCESS = 'ASSIGN_BRANCH_SUCCESS'
export const ASSIGN_BRANCH_ERROR = 'ASSIGN_BRANCH_ERROR'