export const LOADING = "LOADING";
export const GET_USER_PROJECTS_ERROR = 'GET_USER_PROJECTS_ERROR'
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS'

export const GET_GLOBAL_PROJECTS_ERROR = 'GET_GLOBAL_PROJECTS_ERROR'
export const GET_GLOBAL_PROJECTS_SUCCESS = 'GET_GLOBAL_PROJECTS_SUCCESS'

export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'

export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR'

export const EDIT_PROJECT_ERROR = 'EDIT_PROJECT_ERROR'
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS'


// Pull Requests
export const GET_PULL_REQUEST_SUCCESS = 'GET_PULL_REQUEST_SUCCESS'
export const GET_PULL_REQUEST_ERROR = 'GET_PULL_REQUEST_ERROR'

export const GET_PROJECT_PULL_REQUESTS_SUCCESS = 'GET_PROJECT_PULL_REQUESTS_SUCCESS'
export const GET_PROJECT_PULL_REQUESTS_ERROR = 'GET_PULL_REQUESTS_ERROR'


export const GET_GLOBAL_PULL_REQUESTS_SUCCESS = 'GET_GLOBAL_PULL_REQUESTS_SUCCESS'
export const GET_GLOBAL_PULL_REQUESTS_ERROR = 'GET_GLOBAL_PULL_REQUESTS_ERROR'


export const CREATE_PULL_REQUEST_SUCCESS = 'CREATE_PULL_REQUESTS_SUCCESS'
export const CREATE_PULL_REQUEST_ERROR = 'CREATE_PULL_REQUESTS_ERROR'


export const EDIT_PULL_REQUEST_SUCCESS = 'EDIT_PULL_REQUEST_SUCCESS'
export const EDIT_PULL_REQUEST_ERROR = 'EDIT_PULL_REQUEST_ERROR'

export const ASSIGN_PULL_REQUEST_SUCCESS = 'ASSIGN_PULL_REQUEST_SUCCESS'
export const ASSIGN_PULL_REQUEST_ERROR = 'ASSIGN_PULL_REQUEST_ERROR'
